### PR TITLE
fix: support for using alerting in native mode

### LINKED ISSUE #462: [alerting] `rocketpool node status` should not fail if alert manager can't be reached
From discussion with Joe at https://discord.com/channels/405159462932971535/704214707904446535/1219731070489067560

### LINKED ISSUE #463: [alerting] Alert manager should have an explicit enable option, so you can have metrics w/o alerts and vice versa
From discussion at https://discord.com/channels/405159462932971535/704214707904446535/1219731070489067560

### PR DESCRIPTION
**Pull request by activescott**
- Adds a new Alertmanger host config that is only used in native mode
- The AlertingConfigPage is was made reusable so it works in both native mode config and docker config
fixes #462
fixes #463

Related to rocket-pool/docs.rocketpool.net#79

Keeping this a draft pending:
- [x] #463 (fixed herein)
- [x] #464 (fixed in rocket-pool/smartnode-install#123)

### CODE REVIEW

File: rocketpool/api/node/status.go [hunk 1]
```diff
@@ -233,7 +234,10 @@ func getStatus(c *cli.Context) (*api.NodeStatusResponse, error) {
 	wg.Go(func() error {
 		alerts, err := alerting.FetchAlerts(cfg)
 		if err != nil {
-			return err
+			// no reason to make `rocketpool node status` fail if we can't get alerts
+			// (this is more likely to happen in native mode than docker where
+			// alertmanager is more complex to set up)
+			alerts = make([]*models.GettableAlert, 0)
```
Comment (jclapis) [inline rocketpool/api/node/status.go:240]: Suggest printing a little warning or something here so the user knows that there was an issue getting alerts, just a `printf` without erroring out would be fine; otherwise it looks like there aren't any, which may not be strictly true. I submit that the lack of an alert manager when one is enabled is alert-worthy by itself.

File: rocketpool-cli/service/config/settings-alerting.go [hunk 2]
```diff
@@ -40,13 +66,35 @@ func (configPage *AlertingConfigPage) getPage() *page {
 func (configPage *AlertingConfigPage) createContent() {
 	configPage.layout = newStandardLayout()
 	configPage.layout.createForm(&configPage.masterConfig.Smartnode.Network, "Alerting Settings")
-	configPage.layout.setupEscapeReturnHomeHandler(configPage.home.md, configPage.home.homePage)
+	configPage.layout.setupEscapeReturnHomeHandler(configPage.mainDisplay, configPage.homePage)
 
 	// Set up the UI components
-	configPage.alertmanagerItems = createParameterizedFormItems(configPage.masterConfig.Alertmanager.GetParameters(), configPage.layout.descriptionBox)
+	allItems := createParameterizedFormItems(configPage.masterConfig.Alertmanager.GetParameters(), configPage.layout.descriptionBox)
```
Comment (jclapis) [inline rocketpool-cli/service/config/settings-alerting.go:72]: See commentary in `alertmanager-config`.

File: shared/services/config/alertmanager-config.go [hunk 3]
```diff
@@ -196,29 +231,51 @@ func createParameterForAlertEnablement(uniqueName string, label string) config.P
 }
 
 func (cfg *AlertmanagerConfig) GetParameters() []*config.Parameter {
-	return []*config.Parameter{
+	parameters := make([]*config.Parameter, 0, 23)
```
[the remark this answers is not in the document]
Comment (activescott) [reply shared/services/config/alertmanager-config.go]: Ack. Implemented in 03a0cdb7

File: shared/services/config/alertmanager-config.go [hunk 4]
```diff
@@ -64,15 +75,39 @@ type AlertmanagerConfig struct {
...
+			AffectsContainers:  []config.ContainerID{config.ContainerID_Node, config.ContainerID_Prometheus, config.ContainerID_Alertmanager},
+			CanBeBlank:         false,
+			OverwriteOnUpgrade: false,
+		},
+
 		Port: config.Parameter{
 			ID:                 "port",
 			Name:               "Alertmanager Port",
-			Description:        "The port Alertmanager will listen on.",
+			Description:        "The port Alertmanager will listen on. If using Native Mode, this is the port the node will connect to Alertmanager.",
```
[the remark this answers is not in the document]
Comment (activescott) [reply shared/services/config/alertmanager-config.go]: Done in 03a0cdb7

File: rocketpool/api/node/status.go (hunk 1 above)
Comment (activescott) [reply rocketpool/api/node/status.go:242]: Agree it is worthy to make user aware. printf is a bit tough here since it is in the api container. I added a Warning to the struct so we can marshal the warning message back to the user but keep `rocketpool node status` resilient in the face of misconfigured/broken alertmanager. Done in e95fafcb

**Comment by activescott** [comment]
@jclapis Thanks for the review. I resolved your feedback.

**Comment by jclapis** [comment]
Alright, thanks for the updates. Let's give it a test.
